/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import java.awt.Image;
import java.io.IOException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Swarnveer
 */
public class gameOptions extends javax.swing.JFrame {

    /**
     * Creates new form gameOptions
     * 
     *
     */
    private int indexTheme;
    private String p1Name,p2Name;
    private String background;
    private Image image;
    private String p1Image, p2Image, difficulty="hard";
    private int p1Index, p2Index, gameType, gameField, firstTurn;
    
    public gameOptions() {
        initComponents();
        setSize(720,764);
        setLocationRelativeTo(null);
    }

    public gameOptions(int theme) {
        initComponents();
        indexTheme=theme;
        setSize(720,764);
        setLocationRelativeTo(null);
        
   
        switch(indexTheme){
            case 0: background="planets.png";
            p1ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Earth", "Mars", "Jupiter", "Saturn" }));
            p2ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Earth", "Mars", "Jupiter", "Saturn" }));
                    break;
            case 1: background="tomandjerry.jpg";
            p1ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tom", "Jerry" }));
            p2ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tom", "Jerry" }));
                   break;
            case 2: background="pokemon.png";
            p1ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pikachu", "Chikorita", "Bulbasaur", "Charmender", "Squirtle", "Mewto", "Charizard", "Lapras", "Dragonite" }));
            p2ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pikachu", "Chikorita", "Bulbasaur", "Charmender", "Squirtle", "Mewto", "Charizard", "Lapras", "Dragonite" }));
                   break;
            case 3: background="superheroes1.png";
            p1ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Superman", "Batman", "Iron Man", "Captain America", "Green Lantern", "Spiderman", "Wolverine", "Flash", "Hulk", "Wonder Woman"}));
            p2ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Superman", "Batman", "Iron Man", "Captain America", "Green Lantern", "Spiderman", "Wolverine", "Flash", "Hulk", "Wonder Woman"}));
            
            break;
                   
            default: background="pokemon.png";
                    break;
        }
             p2ImageBox.setSelectedIndex((p1Index+1)%p2ImageBox.getComponentCount());
        try {
                image = ImageIO.read(getClass().getResource("CartoonImages/"+background));
            } catch (IOException ex) {
                Logger.getLogger(playerVSplayer.class.getName()).log(Level.SEVERE, null, ex);
            }
        gameOptionsBackground.setIcon(new ImageIcon(image));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        difficultyDialog = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        easy = new javax.swing.JRadioButton();
        medium = new javax.swing.JRadioButton();
        hard = new javax.swing.JRadioButton();
        cancel = new javax.swing.JButton();
        done = new javax.swing.JButton();
        difficultyButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        player1Field = new javax.swing.JTextField();
        player2Field = new javax.swing.JTextField();
        gameTypeComboBox = new javax.swing.JComboBox<>();
        firstTurnComboBox = new javax.swing.JComboBox<>();
        gameFieldComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        p1ImageBox = new javax.swing.JComboBox<>();
        p2ImageBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gameOptionsBackground = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        difficultyDialog.setLocation(new java.awt.Point(450, 250));
        difficultyDialog.setUndecorated(true);
        difficultyDialog.setResizable(false);

        jLabel9.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel9.setText("CHOOSE DIFFICULTY");
        jLabel9.setMaximumSize(new java.awt.Dimension(300, 33));
        jLabel9.setMinimumSize(new java.awt.Dimension(300, 33));
        jLabel9.setPreferredSize(new java.awt.Dimension(300, 33));

        difficultyButtonGroup.add(easy);
        easy.setFont(new java.awt.Font("Lithos Pro Regular", 1, 14)); // NOI18N
        easy.setSelected(true);
        easy.setText("EASY");
        easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyActionPerformed(evt);
            }
        });

        difficultyButtonGroup.add(medium);
        medium.setFont(new java.awt.Font("Lithos Pro Regular", 1, 14)); // NOI18N
        medium.setText("MEDIUM");
        medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumActionPerformed(evt);
            }
        });

        difficultyButtonGroup.add(hard);
        hard.setFont(new java.awt.Font("Lithos Pro Regular", 1, 14)); // NOI18N
        hard.setText("HARD");

        cancel.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        done.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        done.setText("DONE");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout difficultyDialogLayout = new javax.swing.GroupLayout(difficultyDialog.getContentPane());
        difficultyDialog.getContentPane().setLayout(difficultyDialogLayout);
        difficultyDialogLayout.setHorizontalGroup(
            difficultyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(difficultyDialogLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(difficultyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(difficultyDialogLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(difficultyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(difficultyDialogLayout.createSequentialGroup()
                                .addComponent(cancel)
                                .addGap(36, 36, 36)
                                .addComponent(done))
                            .addGroup(difficultyDialogLayout.createSequentialGroup()
                                .addComponent(easy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(medium)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hard)))))
                .addGap(93, 93, 93))
        );
        difficultyDialogLayout.setVerticalGroup(
            difficultyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(difficultyDialogLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(difficultyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(easy)
                    .addComponent(medium)
                    .addComponent(hard))
                .addGap(31, 31, 31)
                .addGroup(difficultyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(done))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(720, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("3 T's");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setPreferredSize(new java.awt.Dimension(192, 76));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(264, 0, 192, 76);

        jLabel2.setBackground(new java.awt.Color(153, 255, 153));
        jLabel2.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PLAYER 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 154, 129, 25);

        jLabel3.setBackground(new java.awt.Color(153, 255, 153));
        jLabel3.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Player 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 228, 120, 25);

        jLabel4.setBackground(new java.awt.Color(153, 255, 153));
        jLabel4.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GaME type");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 302, 144, 25);

        jLabel5.setBackground(new java.awt.Color(153, 255, 153));
        jLabel5.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("First Turn");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 376, 170, 25);

        jLabel6.setBackground(new java.awt.Color(153, 255, 153));
        jLabel6.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("game field");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 450, 142, 25);

        player1Field.setFont(new java.awt.Font("Magneto", 1, 18)); // NOI18N
        player1Field.setText("Player 1");
        player1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1FieldActionPerformed(evt);
            }
        });
        getContentPane().add(player1Field);
        player1Field.setBounds(499, 154, 201, 29);

        player2Field.setFont(new java.awt.Font("Magneto", 1, 18)); // NOI18N
        player2Field.setText("Player 2");
        player2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2FieldActionPerformed(evt);
            }
        });
        getContentPane().add(player2Field);
        player2Field.setBounds(499, 228, 201, 29);

        gameTypeComboBox.setFont(new java.awt.Font("Magneto", 1, 18)); // NOI18N
        gameTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Player Vs Player", "Player Vs Cpu" }));
        gameTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gameTypeComboBoxItemStateChanged(evt);
            }
        });
        getContentPane().add(gameTypeComboBox);
        gameTypeComboBox.setBounds(499, 302, 201, 29);

        firstTurnComboBox.setFont(new java.awt.Font("Magneto", 1, 18)); // NOI18N
        firstTurnComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { player1Field.getText().toString(), player2Field.getText().toString()}));
        getContentPane().add(firstTurnComboBox);
        firstTurnComboBox.setBounds(499, 376, 201, 29);

        gameFieldComboBox.setFont(new java.awt.Font("Magneto", 1, 18)); // NOI18N
        gameFieldComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3X3", "4X4" }));
        getContentPane().add(gameFieldComboBox);
        gameFieldComboBox.setBounds(509, 450, 191, 29);

        jLabel10.setBackground(new java.awt.Color(153, 255, 153));
        jLabel10.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("player 1's");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 524, 135, 25);

        jLabel11.setBackground(new java.awt.Color(153, 255, 153));
        jLabel11.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("character");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 549, 148, 25);

        jLabel12.setBackground(new java.awt.Color(153, 255, 153));
        jLabel12.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("player 2's");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(509, 524, 191, 25);

        jLabel13.setBackground(new java.awt.Color(153, 255, 153));
        jLabel13.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("character");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(509, 549, 191, 25);

        p1ImageBox.setFont(new java.awt.Font("Magneto", 1, 18)); // NOI18N
        if(indexTheme==2)
        p1ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pikachu", "Chikorita", "Bulbasaur", "Charmender", "Squirtle", "Mewto", "Charizard", "Lapras", "Dragonite" }));
        else if(indexTheme==0)
        p1ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Earth", "Mars", "Jupiter", "Saturn" }));
        else if(indexTheme==1)
        p1ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tom", "Jerry" }));
        else if(indexTheme==3)
        p1ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Superman", "Batman", "Iron Man", "Captain America", "Green Lantern", "Spiderman", "Wolverine", "Flash", "Hulk", "Wonder Woman"}));
        p1ImageBox.setMaximumSize(new java.awt.Dimension(75, 29));
        p1ImageBox.setMinimumSize(new java.awt.Dimension(75, 29));
        p1ImageBox.setPreferredSize(new java.awt.Dimension(75, 29));
        p1ImageBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ImageBoxActionPerformed(evt);
            }
        });
        getContentPane().add(p1ImageBox);
        p1ImageBox.setBounds(20, 580, 157, 29);

        p2ImageBox.setFont(new java.awt.Font("Magneto", 1, 18)); // NOI18N
        if(indexTheme==0)
        p2ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Earth", "Mars", "Jupiter", "Saturn" }));
        else if(indexTheme==1)
        p1ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tom", "Jerry" }));
        else if(indexTheme==2)
        p1ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pikachu", "Chikorita", "Bulbasaur", "Charmender", "Squirtle", "Mewto", "Charizard", "Lapras", "Dragonite" }));
        else if(indexTheme==3)
        p1ImageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Superman", "Batman", "Iron Man", "Captain America", "Green Lantern", "Spiderman", "Wolverine", "Flash", "Hulk", "Wonder Woman"}));
        getContentPane().add(p2ImageBox);
        p2ImageBox.setBounds(500, 580, 200, 29);

        jButton1.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        jButton1.setText("Play Now !");
        jButton1.setMaximumSize(new java.awt.Dimension(182, 33));
        jButton1.setMinimumSize(new java.awt.Dimension(182, 33));
        jButton1.setPreferredSize(new java.awt.Dimension(182, 33));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(264, 694, 182, 33);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/CartoonImages/back.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 0, 48, 38);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/CartoonImages/cross.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(660, 0, 50, 50);

        gameOptionsBackground.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(gameOptionsBackground);
        gameOptionsBackground.setBounds(0, 0, 720, 764);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(320, 370, 0, 0);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void player1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player1FieldActionPerformed

    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        p1Name=player1Field.getText().toString();
        p2Name=player2Field.getText().toString();
        p1Index=p1ImageBox.getSelectedIndex();
        p2Index=p2ImageBox.getSelectedIndex();
        gameType=gameTypeComboBox.getSelectedIndex();
        gameField=gameFieldComboBox.getSelectedIndex();
        firstTurn=firstTurnComboBox.getSelectedIndex();
        
        if(p1Index==p2Index)
            p2ImageBox.setSelectedIndex((p1Index+1)%p2ImageBox.getItemCount());
        p1Image=p1ImageBox.getSelectedItem().toString().toLowerCase();
        p2Image=p2ImageBox.getSelectedItem().toString().toLowerCase();
        dispose();
        
        if(gameType==0&&gameField==0){
        playerVSplayer player = new playerVSplayer(p1Name,p2Name,indexTheme,p1Image,p2Image,firstTurn);
        player.setVisible(true);
        }
        else if(gameType==0&&gameField==1){
        playerVSplayerBig player2 = new playerVSplayerBig(p1Name,p2Name,indexTheme,p1Image,p2Image,firstTurn);
        player2.setVisible(true);
        }
        else if(gameType==1&&gameField==0){
        playerVScpu player3 = new playerVScpu(p1Name,p2Name,indexTheme,p1Image,p2Image,firstTurn,difficulty);
       
        player3.setVisible(true);
        }
        
        else if(gameType==1&&gameField==1){
        playerVScpuBig player4 = new playerVScpuBig(p1Name,p2Name,indexTheme,p1Image,p2Image,firstTurn,difficulty);
       
        player4.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        MainScreen obj = new MainScreen();
        obj.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void player2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2FieldActionPerformed
        // TODO add your handling code here:.
    }//GEN-LAST:event_player2FieldActionPerformed

    private void p1ImageBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ImageBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ImageBoxActionPerformed

    private void easyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_easyActionPerformed

    private void mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediumActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        difficulty = getSelectedButtonText(difficultyButtonGroup);
        difficultyDialog.setVisible(false);
        
    }//GEN-LAST:event_doneActionPerformed

    private void gameTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gameTypeComboBoxItemStateChanged
        // TODO add your handling code here:
        difficultyDialog.setSize(486, 319);
        setLocationRelativeTo(null);
        if(gameTypeComboBox.getSelectedIndex()!=0){
            difficultyDialog.setVisible(true);
        }
    }//GEN-LAST:event_gameTypeComboBoxItemStateChanged

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
         difficultyDialog.setVisible(false);
         gameTypeComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        try {
            // Set cross-platform Java L&F (also called "Metal")
        UIManager.setLookAndFeel(
            UIManager.getCrossPlatformLookAndFeelClassName());
    } 
    catch (UnsupportedLookAndFeelException e) {
       // handle exception
    }
    catch (ClassNotFoundException e) {
       // handle exception
    }
    catch (InstantiationException e) {
       // handle exception
    }
    catch (IllegalAccessException e) {
       // handle exception
    }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.ButtonGroup difficultyButtonGroup;
    private javax.swing.JDialog difficultyDialog;
    private javax.swing.JButton done;
    private javax.swing.JRadioButton easy;
    private javax.swing.JComboBox<String> firstTurnComboBox;
    private javax.swing.JComboBox<String> gameFieldComboBox;
    private javax.swing.JLabel gameOptionsBackground;
    private javax.swing.JComboBox<String> gameTypeComboBox;
    private javax.swing.JRadioButton hard;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton medium;
    private javax.swing.JComboBox<String> p1ImageBox;
    private javax.swing.JComboBox<String> p2ImageBox;
    private javax.swing.JTextField player1Field;
    private javax.swing.JTextField player2Field;
    // End of variables declaration//GEN-END:variables
}
